title: Goblin Node Documentation
description: Manual, Privacy Policy, and Support for Goblin Node
theme: minima
url: "https://rainerweston.github.io"
baseurl: "/goblin-node-docs"

markdown: kramdown
plugins:
  - jekyll-feed
